version: '3.8'

services:
  db:
    container_name: db
    image: mysql:5.7.30
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
  api:
    container_name: api
    build: ./api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 5000:3000 
    depends_on:
      - db
    volumes:
      - ./api:/app:cached
      - bundle:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

  front:
    container_name: front
    build: ./front
    volumes:
      - ./front:/app
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: yarn run dev
    

volumes:
  mysql_data:
  bundle: